apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrapers-cron
spec:
  schedule: "0 1,13 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scrapers-container
            image: eu.gcr.io/cerebel-prod/scrapers@sha256:_SHA_
            imagePullPolicy: Always
          restartPolicy: Never
