// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed.proto

package feed

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPageRequest_Gender int32

const (
	GetPageRequest_ALL   GetPageRequest_Gender = 0
	GetPageRequest_WOMEN GetPageRequest_Gender = 1
	GetPageRequest_MEN   GetPageRequest_Gender = 2
)

var GetPageRequest_Gender_name = map[int32]string{
	0: "ALL",
	1: "WOMEN",
	2: "MEN",
}

var GetPageRequest_Gender_value = map[string]int32{
	"ALL":   0,
	"WOMEN": 1,
	"MEN":   2,
}

func (x GetPageRequest_Gender) String() string {
	return proto.EnumName(GetPageRequest_Gender_name, int32(x))
}

func (GetPageRequest_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{4, 0}
}

type CreateStoreRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoreRequest) Reset()         { *m = CreateStoreRequest{} }
func (m *CreateStoreRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStoreRequest) ProtoMessage()    {}
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{0}
}

func (m *CreateStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreRequest.Unmarshal(m, b)
}
func (m *CreateStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreRequest.Marshal(b, m, deterministic)
}
func (m *CreateStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreRequest.Merge(m, src)
}
func (m *CreateStoreRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStoreRequest.Size(m)
}
func (m *CreateStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreRequest proto.InternalMessageInfo

type CreateStoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoreResponse) Reset()         { *m = CreateStoreResponse{} }
func (m *CreateStoreResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStoreResponse) ProtoMessage()    {}
func (*CreateStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{1}
}

func (m *CreateStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreResponse.Unmarshal(m, b)
}
func (m *CreateStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreResponse.Marshal(b, m, deterministic)
}
func (m *CreateStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreResponse.Merge(m, src)
}
func (m *CreateStoreResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStoreResponse.Size(m)
}
func (m *CreateStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreResponse proto.InternalMessageInfo

type DeleteStoreRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoreRequest) Reset()         { *m = DeleteStoreRequest{} }
func (m *DeleteStoreRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreRequest) ProtoMessage()    {}
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{2}
}

func (m *DeleteStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoreRequest.Unmarshal(m, b)
}
func (m *DeleteStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoreRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoreRequest.Merge(m, src)
}
func (m *DeleteStoreRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStoreRequest.Size(m)
}
func (m *DeleteStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoreRequest proto.InternalMessageInfo

type DeleteStoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoreResponse) Reset()         { *m = DeleteStoreResponse{} }
func (m *DeleteStoreResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreResponse) ProtoMessage()    {}
func (*DeleteStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{3}
}

func (m *DeleteStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoreResponse.Unmarshal(m, b)
}
func (m *DeleteStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoreResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoreResponse.Merge(m, src)
}
func (m *DeleteStoreResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStoreResponse.Size(m)
}
func (m *DeleteStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoreResponse proto.InternalMessageInfo

type GetPageRequest struct {
	Nb                   int32                 `protobuf:"varint,1,opt,name=nb,proto3" json:"nb,omitempty"`
	Size                 int32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Gender               GetPageRequest_Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=feed.GetPageRequest_Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetPageRequest) Reset()         { *m = GetPageRequest{} }
func (m *GetPageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPageRequest) ProtoMessage()    {}
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{4}
}

func (m *GetPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageRequest.Unmarshal(m, b)
}
func (m *GetPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageRequest.Marshal(b, m, deterministic)
}
func (m *GetPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageRequest.Merge(m, src)
}
func (m *GetPageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPageRequest.Size(m)
}
func (m *GetPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageRequest proto.InternalMessageInfo

func (m *GetPageRequest) GetNb() int32 {
	if m != nil {
		return m.Nb
	}
	return 0
}

func (m *GetPageRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetPageRequest) GetGender() GetPageRequest_Gender {
	if m != nil {
		return m.Gender
	}
	return GetPageRequest_ALL
}

type GetPageResponse struct {
	Records              []byte   `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPageResponse) Reset()         { *m = GetPageResponse{} }
func (m *GetPageResponse) String() string { return proto.CompactTextString(m) }
func (*GetPageResponse) ProtoMessage()    {}
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{5}
}

func (m *GetPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageResponse.Unmarshal(m, b)
}
func (m *GetPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageResponse.Marshal(b, m, deterministic)
}
func (m *GetPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageResponse.Merge(m, src)
}
func (m *GetPageResponse) XXX_Size() int {
	return xxx_messageInfo_GetPageResponse.Size(m)
}
func (m *GetPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageResponse proto.InternalMessageInfo

func (m *GetPageResponse) GetRecords() []byte {
	if m != nil {
		return m.Records
	}
	return nil
}

type ListPromotionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPromotionsRequest) Reset()         { *m = ListPromotionsRequest{} }
func (m *ListPromotionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPromotionsRequest) ProtoMessage()    {}
func (*ListPromotionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{6}
}

func (m *ListPromotionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPromotionsRequest.Unmarshal(m, b)
}
func (m *ListPromotionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPromotionsRequest.Marshal(b, m, deterministic)
}
func (m *ListPromotionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPromotionsRequest.Merge(m, src)
}
func (m *ListPromotionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPromotionsRequest.Size(m)
}
func (m *ListPromotionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPromotionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPromotionsRequest proto.InternalMessageInfo

type ListPromotionsResponse struct {
	Records              []byte   `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPromotionsResponse) Reset()         { *m = ListPromotionsResponse{} }
func (m *ListPromotionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPromotionsResponse) ProtoMessage()    {}
func (*ListPromotionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{7}
}

func (m *ListPromotionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPromotionsResponse.Unmarshal(m, b)
}
func (m *ListPromotionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPromotionsResponse.Marshal(b, m, deterministic)
}
func (m *ListPromotionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPromotionsResponse.Merge(m, src)
}
func (m *ListPromotionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPromotionsResponse.Size(m)
}
func (m *ListPromotionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPromotionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPromotionsResponse proto.InternalMessageInfo

func (m *ListPromotionsResponse) GetRecords() []byte {
	if m != nil {
		return m.Records
	}
	return nil
}

type Promotion struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Position             int32    `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Promotion) Reset()         { *m = Promotion{} }
func (m *Promotion) String() string { return proto.CompactTextString(m) }
func (*Promotion) ProtoMessage()    {}
func (*Promotion) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{8}
}

func (m *Promotion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Promotion.Unmarshal(m, b)
}
func (m *Promotion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Promotion.Marshal(b, m, deterministic)
}
func (m *Promotion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Promotion.Merge(m, src)
}
func (m *Promotion) XXX_Size() int {
	return xxx_messageInfo_Promotion.Size(m)
}
func (m *Promotion) XXX_DiscardUnknown() {
	xxx_messageInfo_Promotion.DiscardUnknown(m)
}

var xxx_messageInfo_Promotion proto.InternalMessageInfo

func (m *Promotion) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Promotion) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Promotion) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Promotion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddPromotionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPromotionResponse) Reset()         { *m = AddPromotionResponse{} }
func (m *AddPromotionResponse) String() string { return proto.CompactTextString(m) }
func (*AddPromotionResponse) ProtoMessage()    {}
func (*AddPromotionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{9}
}

func (m *AddPromotionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPromotionResponse.Unmarshal(m, b)
}
func (m *AddPromotionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPromotionResponse.Marshal(b, m, deterministic)
}
func (m *AddPromotionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPromotionResponse.Merge(m, src)
}
func (m *AddPromotionResponse) XXX_Size() int {
	return xxx_messageInfo_AddPromotionResponse.Size(m)
}
func (m *AddPromotionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPromotionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPromotionResponse proto.InternalMessageInfo

type DeletePromotionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePromotionResponse) Reset()         { *m = DeletePromotionResponse{} }
func (m *DeletePromotionResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePromotionResponse) ProtoMessage()    {}
func (*DeletePromotionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{10}
}

func (m *DeletePromotionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePromotionResponse.Unmarshal(m, b)
}
func (m *DeletePromotionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePromotionResponse.Marshal(b, m, deterministic)
}
func (m *DeletePromotionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePromotionResponse.Merge(m, src)
}
func (m *DeletePromotionResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePromotionResponse.Size(m)
}
func (m *DeletePromotionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePromotionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePromotionResponse proto.InternalMessageInfo

type SetItemsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemIds              []string `protobuf:"bytes,2,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetItemsRequest) Reset()         { *m = SetItemsRequest{} }
func (m *SetItemsRequest) String() string { return proto.CompactTextString(m) }
func (*SetItemsRequest) ProtoMessage()    {}
func (*SetItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{11}
}

func (m *SetItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetItemsRequest.Unmarshal(m, b)
}
func (m *SetItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetItemsRequest.Marshal(b, m, deterministic)
}
func (m *SetItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetItemsRequest.Merge(m, src)
}
func (m *SetItemsRequest) XXX_Size() int {
	return xxx_messageInfo_SetItemsRequest.Size(m)
}
func (m *SetItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetItemsRequest proto.InternalMessageInfo

func (m *SetItemsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetItemsRequest) GetItemIds() []string {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

type SetItemsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetItemsResponse) Reset()         { *m = SetItemsResponse{} }
func (m *SetItemsResponse) String() string { return proto.CompactTextString(m) }
func (*SetItemsResponse) ProtoMessage()    {}
func (*SetItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{12}
}

func (m *SetItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetItemsResponse.Unmarshal(m, b)
}
func (m *SetItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetItemsResponse.Marshal(b, m, deterministic)
}
func (m *SetItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetItemsResponse.Merge(m, src)
}
func (m *SetItemsResponse) XXX_Size() int {
	return xxx_messageInfo_SetItemsResponse.Size(m)
}
func (m *SetItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetItemsResponse proto.InternalMessageInfo

type DeleteByIDsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByIDsRequest) Reset()         { *m = DeleteByIDsRequest{} }
func (m *DeleteByIDsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteByIDsRequest) ProtoMessage()    {}
func (*DeleteByIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{13}
}

func (m *DeleteByIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByIDsRequest.Unmarshal(m, b)
}
func (m *DeleteByIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByIDsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteByIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByIDsRequest.Merge(m, src)
}
func (m *DeleteByIDsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteByIDsRequest.Size(m)
}
func (m *DeleteByIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByIDsRequest proto.InternalMessageInfo

func (m *DeleteByIDsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type DeleteByIDsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByIDsResponse) Reset()         { *m = DeleteByIDsResponse{} }
func (m *DeleteByIDsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteByIDsResponse) ProtoMessage()    {}
func (*DeleteByIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{14}
}

func (m *DeleteByIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByIDsResponse.Unmarshal(m, b)
}
func (m *DeleteByIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByIDsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteByIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByIDsResponse.Merge(m, src)
}
func (m *DeleteByIDsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteByIDsResponse.Size(m)
}
func (m *DeleteByIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByIDsResponse proto.InternalMessageInfo

type Source struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{15}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Source) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AddSourceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSourceResponse) Reset()         { *m = AddSourceResponse{} }
func (m *AddSourceResponse) String() string { return proto.CompactTextString(m) }
func (*AddSourceResponse) ProtoMessage()    {}
func (*AddSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{16}
}

func (m *AddSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSourceResponse.Unmarshal(m, b)
}
func (m *AddSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSourceResponse.Marshal(b, m, deterministic)
}
func (m *AddSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSourceResponse.Merge(m, src)
}
func (m *AddSourceResponse) XXX_Size() int {
	return xxx_messageInfo_AddSourceResponse.Size(m)
}
func (m *AddSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSourceResponse proto.InternalMessageInfo

type DeleteSourceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSourceResponse) Reset()         { *m = DeleteSourceResponse{} }
func (m *DeleteSourceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSourceResponse) ProtoMessage()    {}
func (*DeleteSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{17}
}

func (m *DeleteSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSourceResponse.Unmarshal(m, b)
}
func (m *DeleteSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSourceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSourceResponse.Merge(m, src)
}
func (m *DeleteSourceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSourceResponse.Size(m)
}
func (m *DeleteSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSourceResponse proto.InternalMessageInfo

type ListSourcesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSourcesRequest) Reset()         { *m = ListSourcesRequest{} }
func (m *ListSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ListSourcesRequest) ProtoMessage()    {}
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{18}
}

func (m *ListSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSourcesRequest.Unmarshal(m, b)
}
func (m *ListSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSourcesRequest.Marshal(b, m, deterministic)
}
func (m *ListSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSourcesRequest.Merge(m, src)
}
func (m *ListSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ListSourcesRequest.Size(m)
}
func (m *ListSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSourcesRequest proto.InternalMessageInfo

type ListSourcesResponse struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListSourcesResponse) Reset()         { *m = ListSourcesResponse{} }
func (m *ListSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ListSourcesResponse) ProtoMessage()    {}
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{19}
}

func (m *ListSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSourcesResponse.Unmarshal(m, b)
}
func (m *ListSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSourcesResponse.Marshal(b, m, deterministic)
}
func (m *ListSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSourcesResponse.Merge(m, src)
}
func (m *ListSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ListSourcesResponse.Size(m)
}
func (m *ListSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSourcesResponse proto.InternalMessageInfo

func (m *ListSourcesResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

func init() {
	proto.RegisterEnum("feed.GetPageRequest_Gender", GetPageRequest_Gender_name, GetPageRequest_Gender_value)
	proto.RegisterType((*CreateStoreRequest)(nil), "feed.CreateStoreRequest")
	proto.RegisterType((*CreateStoreResponse)(nil), "feed.CreateStoreResponse")
	proto.RegisterType((*DeleteStoreRequest)(nil), "feed.DeleteStoreRequest")
	proto.RegisterType((*DeleteStoreResponse)(nil), "feed.DeleteStoreResponse")
	proto.RegisterType((*GetPageRequest)(nil), "feed.GetPageRequest")
	proto.RegisterType((*GetPageResponse)(nil), "feed.GetPageResponse")
	proto.RegisterType((*ListPromotionsRequest)(nil), "feed.ListPromotionsRequest")
	proto.RegisterType((*ListPromotionsResponse)(nil), "feed.ListPromotionsResponse")
	proto.RegisterType((*Promotion)(nil), "feed.Promotion")
	proto.RegisterType((*AddPromotionResponse)(nil), "feed.AddPromotionResponse")
	proto.RegisterType((*DeletePromotionResponse)(nil), "feed.DeletePromotionResponse")
	proto.RegisterType((*SetItemsRequest)(nil), "feed.SetItemsRequest")
	proto.RegisterType((*SetItemsResponse)(nil), "feed.SetItemsResponse")
	proto.RegisterType((*DeleteByIDsRequest)(nil), "feed.DeleteByIDsRequest")
	proto.RegisterType((*DeleteByIDsResponse)(nil), "feed.DeleteByIDsResponse")
	proto.RegisterType((*Source)(nil), "feed.Source")
	proto.RegisterType((*AddSourceResponse)(nil), "feed.AddSourceResponse")
	proto.RegisterType((*DeleteSourceResponse)(nil), "feed.DeleteSourceResponse")
	proto.RegisterType((*ListSourcesRequest)(nil), "feed.ListSourcesRequest")
	proto.RegisterType((*ListSourcesResponse)(nil), "feed.ListSourcesResponse")
}

func init() { proto.RegisterFile("feed.proto", fileDescriptor_d7a672c1337cb5ac) }

var fileDescriptor_d7a672c1337cb5ac = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x95, 0xe5, 0x4f, 0x4d, 0x8c, 0xed, 0x4e, 0x1c, 0x47, 0x51, 0x1a, 0x08, 0x82, 0x86, 0x40,
	0xc1, 0x07, 0xa7, 0x87, 0xd2, 0x36, 0x87, 0x34, 0x69, 0x83, 0x21, 0x69, 0x83, 0x42, 0xe9, 0x31,
	0x38, 0xd9, 0x69, 0x10, 0xc4, 0x92, 0xab, 0x5d, 0x53, 0xd2, 0x5f, 0xd1, 0xdf, 0xd7, 0x5f, 0x53,
	0x76, 0xb5, 0x5a, 0xeb, 0x0b, 0x7a, 0x9b, 0x7d, 0x3b, 0xf3, 0xf6, 0x69, 0xde, 0x8c, 0x0d, 0xf0,
	0x83, 0x88, 0x4d, 0x57, 0x49, 0x2c, 0x62, 0x6c, 0xc9, 0xd8, 0x1f, 0x03, 0x9e, 0x27, 0xb4, 0x10,
	0x74, 0x2b, 0xe2, 0x84, 0x02, 0xfa, 0xb9, 0x26, 0x2e, 0xfc, 0x1d, 0xd8, 0x2e, 0xa0, 0x7c, 0x15,
	0x47, 0x9c, 0x64, 0xf2, 0x05, 0x3d, 0x51, 0x35, 0xb9, 0x80, 0xea, 0xe4, 0x3f, 0x0d, 0x18, 0x5c,
	0x92, 0xb8, 0x59, 0x3c, 0x66, 0x99, 0x38, 0x00, 0x3b, 0xba, 0x77, 0x1b, 0x87, 0x8d, 0xe3, 0x76,
	0x60, 0x47, 0xf7, 0x88, 0xd0, 0xe2, 0xe1, 0x6f, 0x72, 0x6d, 0x85, 0xa8, 0x18, 0x4f, 0xa0, 0xf3,
	0x48, 0x11, 0xa3, 0xc4, 0x6d, 0x1e, 0x36, 0x8e, 0x07, 0xb3, 0xfd, 0xa9, 0xd2, 0x5c, 0x64, 0x9a,
	0x5e, 0xaa, 0x94, 0x40, 0xa7, 0xfa, 0xaf, 0xa0, 0x93, 0x22, 0xd8, 0x85, 0xe6, 0xd9, 0xd5, 0xd5,
	0xc8, 0x42, 0x07, 0xda, 0xdf, 0xbf, 0x5e, 0x7f, 0xfa, 0x32, 0x6a, 0x48, 0x4c, 0x06, 0xb6, 0xff,
	0x1a, 0x86, 0x86, 0x27, 0x55, 0x89, 0x2e, 0x74, 0x13, 0x7a, 0x88, 0x13, 0xc6, 0x95, 0xae, 0x7e,
	0x90, 0x1d, 0xfd, 0x5d, 0xd8, 0xb9, 0x0a, 0xb9, 0xb8, 0x49, 0xe2, 0x65, 0x2c, 0xc2, 0x38, 0xe2,
	0xd9, 0xf7, 0xce, 0x60, 0x52, 0xbe, 0xf8, 0x2f, 0xd9, 0x2f, 0x70, 0x4c, 0x3e, 0x1e, 0x00, 0xac,
	0x92, 0x98, 0xad, 0x1f, 0xc4, 0x5d, 0xc8, 0x54, 0xa6, 0x13, 0x38, 0x1a, 0x99, 0x33, 0xdc, 0x07,
	0x27, 0x5c, 0x2e, 0x1e, 0xe9, 0x6e, 0x9d, 0x3c, 0xa9, 0xd6, 0x38, 0x41, 0x4f, 0x01, 0xdf, 0x92,
	0x27, 0xf4, 0xa0, 0xb7, 0x8a, 0x79, 0x28, 0x79, 0x54, 0x83, 0xda, 0x81, 0x39, 0xcb, 0x76, 0x46,
	0x8b, 0x25, 0xb9, 0x2d, 0x55, 0xa3, 0x62, 0x7f, 0x02, 0xe3, 0x33, 0xc6, 0xcc, 0xdb, 0xc6, 0x9d,
	0x3d, 0xd8, 0x4d, 0x4d, 0xab, 0x5e, 0x7d, 0x80, 0xe1, 0x2d, 0x89, 0xb9, 0xa0, 0x25, 0xcf, 0x19,
	0x67, 0x94, 0xda, 0x21, 0xc3, 0x3d, 0xe8, 0x85, 0x82, 0x96, 0x77, 0x21, 0xe3, 0xae, 0x7d, 0xd8,
	0x3c, 0x76, 0x82, 0xae, 0x3c, 0xcf, 0x19, 0xf7, 0x11, 0x46, 0x9b, 0x6a, 0xcd, 0x78, 0x94, 0xcd,
	0xcd, 0xc7, 0xe7, 0xf9, 0x85, 0x21, 0x1d, 0x41, 0x33, 0x54, 0x9d, 0x92, 0xf5, 0x32, 0xdc, 0x4c,
	0x92, 0xce, 0xd3, 0xe5, 0x53, 0xe8, 0xdc, 0xc6, 0xeb, 0xe4, 0x81, 0xe4, 0x17, 0x8a, 0xe7, 0x15,
	0x69, 0x25, 0x2a, 0x96, 0x34, 0x9b, 0x46, 0xc9, 0xd0, 0xdf, 0x86, 0x17, 0x67, 0x8c, 0xa5, 0x25,
	0x86, 0x64, 0x02, 0x63, 0x3d, 0xa5, 0x45, 0x7c, 0x0c, 0x28, 0xdd, 0x4c, 0x51, 0xe3, 0xf1, 0x29,
	0x6c, 0x17, 0x50, 0x6d, 0xf0, 0x11, 0x74, 0x79, 0x0a, 0x29, 0xd9, 0x5b, 0xb3, 0x7e, 0x3a, 0x9d,
	0x9a, 0x33, 0xbb, 0x9c, 0xfd, 0x6d, 0x43, 0xeb, 0x33, 0x11, 0xc3, 0x0b, 0xd8, 0xca, 0x2d, 0x12,
	0xba, 0x69, 0x7a, 0x75, 0xe3, 0xbc, 0xbd, 0x9a, 0x1b, 0xad, 0xd0, 0x92, 0x2c, 0xb9, 0x0d, 0xcb,
	0x58, 0xaa, 0xab, 0x98, 0xb1, 0xd4, 0xad, 0xa3, 0x85, 0x6f, 0xa1, 0xab, 0xa7, 0x1f, 0xc7, 0x75,
	0x4b, 0xe5, 0xed, 0x94, 0xd0, 0xea, 0xfb, 0xca, 0x97, 0xe2, 0xfb, 0x79, 0x4b, 0x8b, 0xef, 0x17,
	0x4d, 0xb4, 0xf0, 0x3d, 0xf4, 0xb2, 0xc9, 0x40, 0xfd, 0x54, 0x69, 0xce, 0xbc, 0x49, 0x19, 0xce,
	0x4b, 0xc8, 0x19, 0x92, 0x49, 0xa8, 0x3a, 0x97, 0x49, 0xa8, 0x71, 0xcf, 0xb7, 0xf0, 0x0d, 0x38,
	0x66, 0x32, 0xb0, 0xe0, 0x9d, 0xb7, 0x9b, 0x9e, 0xaa, 0x83, 0x63, 0xe1, 0x3b, 0xe8, 0xe7, 0x47,
	0xa7, 0x54, 0xe8, 0x15, 0x7a, 0x5e, 0xae, 0xbd, 0x86, 0x41, 0xf1, 0xc7, 0x02, 0xf7, 0x37, 0x02,
	0x2b, 0xbf, 0x2d, 0xde, 0xcb, 0xfa, 0x4b, 0x43, 0x77, 0x0a, 0xfd, 0xfc, 0x3a, 0xe3, 0x30, 0xcd,
	0x37, 0x40, 0xa6, 0xa6, 0x76, 0xe7, 0x2d, 0x3c, 0x87, 0x61, 0x69, 0xeb, 0xab, 0x0c, 0x07, 0xf9,
	0xef, 0xa9, 0x21, 0xb9, 0xef, 0xa8, 0xff, 0x8f, 0x93, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c,
	0x34, 0xdd, 0x08, 0x4d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedClient is the client API for Feed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedClient interface {
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error)
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error)
	DeleteByIDs(ctx context.Context, in *DeleteByIDsRequest, opts ...grpc.CallOption) (*DeleteByIDsResponse, error)
	SetItems(ctx context.Context, in *SetItemsRequest, opts ...grpc.CallOption) (*SetItemsResponse, error)
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	AddSource(ctx context.Context, in *Source, opts ...grpc.CallOption) (*AddSourceResponse, error)
	DeleteSource(ctx context.Context, in *Source, opts ...grpc.CallOption) (*DeleteSourceResponse, error)
	ListPromotions(ctx context.Context, in *ListPromotionsRequest, opts ...grpc.CallOption) (*ListPromotionsResponse, error)
	AddPromotion(ctx context.Context, in *Promotion, opts ...grpc.CallOption) (*AddPromotionResponse, error)
	DeletePromotion(ctx context.Context, in *Promotion, opts ...grpc.CallOption) (*DeletePromotionResponse, error)
}

type feedClient struct {
	cc *grpc.ClientConn
}

func NewFeedClient(cc *grpc.ClientConn) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error) {
	out := new(CreateStoreResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/DeleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error) {
	out := new(GetPageResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) DeleteByIDs(ctx context.Context, in *DeleteByIDsRequest, opts ...grpc.CallOption) (*DeleteByIDsResponse, error) {
	out := new(DeleteByIDsResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/DeleteByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) SetItems(ctx context.Context, in *SetItemsRequest, opts ...grpc.CallOption) (*SetItemsResponse, error) {
	out := new(SetItemsResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/SetItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/ListSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) AddSource(ctx context.Context, in *Source, opts ...grpc.CallOption) (*AddSourceResponse, error) {
	out := new(AddSourceResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/AddSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) DeleteSource(ctx context.Context, in *Source, opts ...grpc.CallOption) (*DeleteSourceResponse, error) {
	out := new(DeleteSourceResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/DeleteSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) ListPromotions(ctx context.Context, in *ListPromotionsRequest, opts ...grpc.CallOption) (*ListPromotionsResponse, error) {
	out := new(ListPromotionsResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/ListPromotions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) AddPromotion(ctx context.Context, in *Promotion, opts ...grpc.CallOption) (*AddPromotionResponse, error) {
	out := new(AddPromotionResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/AddPromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) DeletePromotion(ctx context.Context, in *Promotion, opts ...grpc.CallOption) (*DeletePromotionResponse, error) {
	out := new(DeletePromotionResponse)
	err := c.cc.Invoke(ctx, "/feed.Feed/DeletePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServer is the server API for Feed service.
type FeedServer interface {
	CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error)
	DeleteByIDs(context.Context, *DeleteByIDsRequest) (*DeleteByIDsResponse, error)
	SetItems(context.Context, *SetItemsRequest) (*SetItemsResponse, error)
	ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error)
	AddSource(context.Context, *Source) (*AddSourceResponse, error)
	DeleteSource(context.Context, *Source) (*DeleteSourceResponse, error)
	ListPromotions(context.Context, *ListPromotionsRequest) (*ListPromotionsResponse, error)
	AddPromotion(context.Context, *Promotion) (*AddPromotionResponse, error)
	DeletePromotion(context.Context, *Promotion) (*DeletePromotionResponse, error)
}

// UnimplementedFeedServer can be embedded to have forward compatible implementations.
type UnimplementedFeedServer struct {
}

func (*UnimplementedFeedServer) CreateStore(ctx context.Context, req *CreateStoreRequest) (*CreateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (*UnimplementedFeedServer) DeleteStore(ctx context.Context, req *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (*UnimplementedFeedServer) GetPage(ctx context.Context, req *GetPageRequest) (*GetPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedFeedServer) DeleteByIDs(ctx context.Context, req *DeleteByIDsRequest) (*DeleteByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByIDs not implemented")
}
func (*UnimplementedFeedServer) SetItems(ctx context.Context, req *SetItemsRequest) (*SetItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetItems not implemented")
}
func (*UnimplementedFeedServer) ListSources(ctx context.Context, req *ListSourcesRequest) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (*UnimplementedFeedServer) AddSource(ctx context.Context, req *Source) (*AddSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSource not implemented")
}
func (*UnimplementedFeedServer) DeleteSource(ctx context.Context, req *Source) (*DeleteSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSource not implemented")
}
func (*UnimplementedFeedServer) ListPromotions(ctx context.Context, req *ListPromotionsRequest) (*ListPromotionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPromotions not implemented")
}
func (*UnimplementedFeedServer) AddPromotion(ctx context.Context, req *Promotion) (*AddPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPromotion not implemented")
}
func (*UnimplementedFeedServer) DeletePromotion(ctx context.Context, req *Promotion) (*DeletePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePromotion not implemented")
}

func RegisterFeedServer(s *grpc.Server, srv FeedServer) {
	s.RegisterService(&_Feed_serviceDesc, srv)
}

func _Feed_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_DeleteByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).DeleteByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/DeleteByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).DeleteByIDs(ctx, req.(*DeleteByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_SetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).SetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/SetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).SetItems(ctx, req.(*SetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/ListSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Source)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/AddSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).AddSource(ctx, req.(*Source))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Source)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/DeleteSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).DeleteSource(ctx, req.(*Source))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_ListPromotions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPromotionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).ListPromotions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/ListPromotions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).ListPromotions(ctx, req.(*ListPromotionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_AddPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Promotion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).AddPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/AddPromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).AddPromotion(ctx, req.(*Promotion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_DeletePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Promotion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).DeletePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feed/DeletePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).DeletePromotion(ctx, req.(*Promotion))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feed.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStore",
			Handler:    _Feed_CreateStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _Feed_DeleteStore_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _Feed_GetPage_Handler,
		},
		{
			MethodName: "DeleteByIDs",
			Handler:    _Feed_DeleteByIDs_Handler,
		},
		{
			MethodName: "SetItems",
			Handler:    _Feed_SetItems_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _Feed_ListSources_Handler,
		},
		{
			MethodName: "AddSource",
			Handler:    _Feed_AddSource_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _Feed_DeleteSource_Handler,
		},
		{
			MethodName: "ListPromotions",
			Handler:    _Feed_ListPromotions_Handler,
		},
		{
			MethodName: "AddPromotion",
			Handler:    _Feed_AddPromotion_Handler,
		},
		{
			MethodName: "DeletePromotion",
			Handler:    _Feed_DeletePromotion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feed.proto",
}
