apiVersion: v1
kind: Service
metadata:
  labels:
    run: balancer
  name: balancer
spec:
  ports:
  - port: 80
  selector:
    run: balancer
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: balancer
  name: balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: balancer
  template:
    metadata:
      labels:
        run: balancer
    spec:
      containers:
      - image: eu.gcr.io/cerebel-prod/balancer@sha256:_SHA_
        imagePullPolicy: Always
        name: balancer
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
