apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 8080
    name: http
  - port: 9090
    name: grpc
  - port: 9100
    name: prometheus
  selector:
    app: backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend 
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app: backend
    spec:
      volumes:
      - name: data
        hostPath:
          path: /root/data
      containers:
      - name: backend-container
        image: eu.gcr.io/cerebel-prod/backend@sha256:_SHA_
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 9090 
        - containerPort: 9100
        volumeMounts:
          - name: data
            mountPath: /data
        env:
        - name: ENV
          value: "prod"
        - name: HTTP_PORT
          value: "8080"
        - name: GRPC_PORT
          value: "9090"
        - name: PROMETHEUS_PORT
          value: "9100"
        - name: ELASTIC_HOST
          value: "http://elasticsearch:9200"
        - name: ANNOTATION_HOST
          value: "localhost:9092"
        - name: REDIS_HOST
          value: "redis:6379"
        - name: DATA_PATH
          value: "/data"
      - name: annotation-container
        image: eu.gcr.io/cerebel-prod/annotation@sha256:008a252fb427fd4918ba1dbdc6b3c6a34416f710bb82d0db94c8c4cff9d3f476
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        volumeMounts:
          - name: data
            mountPath: /data
        env:
        - name: ENV
          value: "prod"
        - name: GRPC_PORT
          value: "9092"
        - name: DATA_PATH
          value: "/data"
        - name: USE_CUDA
          value: "false"
