apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feedindexer-cron
spec:
  schedule: "0 3,15 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: feedindexer-container
            image: eu.gcr.io/cerebel-prod/feedindexer@sha256:_SHA_
            env:
            - name: ENV
              value: "prod"
            - name: ELASTIC_HOST
              value: "http://elasticsearch:9200"
            - name: PROMETHEUS_PORT
              value: "9100"
          restartPolicy: OnFailure
