apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  ports:
  - port: 8088
    name: http
  - port: 9100
    name: prometheus
  selector:
    app: homepage
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app: homepage
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homepage-pvc
      containers:
      - name: homepage-container
        image: eu.gcr.io/cerebel-prod/homepage@sha256:_SHA_
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            mountPath: /var/lib/ghost/content
        ports:
        - containerPort: 8088
        - containerPort: 9100
        env:
        - name: ENV
          value: "prod"
        - name: HTTP_PORT
          value: "8088"
        - name: PROMETHEUS_PORT
          value: "9100"
