cluster.name: ${CLUSTER_NAME}

# Required starting from 5.5.2 
# xpack.security.enabled: false

http.host: 0.0.0.0
transport.host: 0.0.0.0

cloud:
  kubernetes:
    service: ${SERVICE}
    namespace: ${NAMESPACE}

discovery:
  zen:
    hosts_provider: kubernetes
    # TODO: split master and data nodes to simplify scaling
    minimum_master_nodes: 1
