apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
  - port: 9300
  selector:
    app: elasticsearch
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elastic-pvc
      containers:
      - name: elastic-container
        # The following image holds elasticsearch:5.2-alpine at the time initial cluster was created
        image: elasticsearch:h@sha256:97694c677327acd6b7b833d0a93fde54b148d5fc8a6702976a85f8a1876cda7e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
